service: sleep-iq-bed

frameworkVersion: "2"

package:
  include:
    - index.js
    - connector.js
    - oauth2.js
    - lib/**
    - config/**
  exclude:
    - .git/**
    - .gitignore
    - .env*
    - test/**
    - server.js
    - bin/**

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

  # replace with closest region to your geographic location for ideal latency
  # see: https://docs.aws.amazon.com/general/latest/gr/rande.html#regional-endpoints
  region: us-east-1 

functions:
  smartapp:
    handler: index.handle
    timeout: 10
